# Dealing with Errors
- If an error happens, the program should
	- return to a safe state and enable the user to execute other commands
	- allow the user to save all the work and terminate the program gracefully

### The Classification of Exceptions

![](Pasted_image_20230812121456.png)

- In java an exception object is an instance of a class derived from `Throwable`.
- The `Error` hierarchy describes **internal errors** and **resource exhaustion** situations inside the Java runtime system. ***You should not throw an object of this type***.
- The `Exception` hierarchy also splits into two branches: exceptions that derive from `RuntimeException` and those that do not.
- A `RuntimeException` happens because you made a programming error.
- Any other exception occurs because a bad thing, such as an I/O error happened.
- Exceptions that inherit from `RuntimeException` include such problems as :
	- A bad Cast
	- An out-of-bounds array access
	- A null pointer access
- Exceptions that do not inherit from `RuntimeException` include :
	- Trying to read past the end of a file
	- Trying to open a file that doesn’t exist
	- Trying to find a `Class` object for a string that does not denote an existing class
- Any exception that derives from the class `Error` or the class `RuntimeException` is an *unchecked* exception, all other exceptions are called *checked* exceptions.
- The compiler checks that you provide exception handlers for all *checked* exceptions.

### Declaring Checked Exceptions
- A method must declare all the ***checked*** exceptions that it might throw separated by comma using `throws` keyword.
- If no handler catches the exception thrown by the method, the current thread of execution terminates.
- ***Unchecked*** exceptions are either beyond your control (`Error`) or result from conditions that you should not have allowed in the first place (`RuntimeException`), so you don't need to throw them.
- If your method fails to faithfully declare all ***checked*** exceptions, the compiler will issue an error message.
- An exception is thrown in any of the following four situations :
	- You call a method that throws a checked exception—for example, the `FileInputStream` constructor.
	- You detect an error and throw a ***checked*** exception with the `throw` statement
	- You make a programming error, that gives rise to an ***unchecked*** exception (`ArrayIndexOutOfBoundsException`)
	- An internal error occurs in the virtual machine or runtime library.
```Java
class MyAnimation
{
	public Image loadImage(String s)throws IOException, EOFException
	{
		. . .
	}
}
```
- If you override a method from a superclass, the ***checked*** exceptions that the subclass method declares cannot be more general than those of the superclass method.
- In particular, if the superclass method throws no checked exception at all, neither can the subclass.
- When a method in a class declares that it throws an exception that is an instance of a particular class, it may throw an exception of that class or of any of its subclasses.

### How to Throw an Exception
- Throwing an exception is easy if one of the existing exception classes works for you. In this case :
	- Find an appropriate exception class.
	- Make an object of that class.
	- Throw it.
```Java
String readData(Scanner in) throws EOFException
{
	. . .
	while(. . .)
	{
		if(!in.hasNext())
		{
			if(n<len)
				throw new EOFException();
			//The EOFException has a second constructor that takes a string argument.
		}
		. . .
	}
	return s;
}
```

### Creating Exception Classes
```Java
class FileFormatException extends IOException
{
	public FileFormatException() {}
	public FileFormatException(String gripe)
	{
		super(gripe);
	}
}

String readData(BufferedReader in) throws FileFormatException
{
	. . .
	while(. . .)
	{
		if(ch == -1)
		{
			if(n<len)
				throw new FIleFormatException();
		}
		. . .
	}
	return s;
}
```
- It is easy enough to create your own exception class. Just derive it from `Exception`, or from a child class of `Exception` such as `IOException`.
- It is customary to give both a **default constructor** and **a constructor that contains a detailed message**.
- The `toString` method of the `Throwable` superclass returns a string containing that detailed message, which is handy for debugging.
- `String getMessage()` : gets the detailed message of the `Throwable` object.

# Catching Exceptions
- If an exception occurs that is not caught anywhere, the program will terminate and print a message to the console, giving the **type of the exception** and a **stack trace**.
- To catch an exception, set up a `try/catch` block.
```Java
try
{
	. . .
}
catch(Exception e)
{
	//handler for this type
}
```
- If any code inside the try block throws an exception of the class specified in the catch clause, then :
	- The program skips the remainder of the code in the `try` block.
	- The program executes the handler code inside the `catch` clause.
- If none of the code inside the `try` block throws an exception, then the program skips the `catch` clause.
- If any of the code in a method throws an exception of a type other than the one named in the catch clause inside the body of the method, this method exits immediately.(Hopefully, one of its callers has already provided a catch clause for that type.)
- Remember, the compiler strictly enforces the `throws` specifiers. If you call a method that throws a *checked* exception, you must either handle it inside the method's body using `try/catch` or pass it on to the caller of the method.

### Catching Multiple Exceptions
```Java
try 
{ 
	code that might throw exceptions 
}
catch (FileNotFoundException e) 
{ 
	emergency action for missing files 
} 
catch (UnknownHostException e) 
{ 
	emergency action for unknown hosts 
} 
catch (IOException e) 
{ 
	emergency action for all other I/O problems 
}
```
- To find out more about the object, try `e.getMessage()` or `e.getClass().getName()` to get the actual type of the exception object.
- you can also combine the catch clauses :
```Java
try { code that might throw exceptions } 

catch (FileNotFoundException | UnknownHostException e) 
{ emergency action for missing files and unknown hosts } 

catch (IOException e) 
{ emergency action for all other I/O problems }
```
- This feature is only needed when catching exception types that are not subclasses of one another.
- When you catch multiple exceptions, the exception variable is implicitly `final`.

### Rethrowing and Chaining Exceptions
- You can throw an exception in a catch clause.
- you do this when you want to change the exception type.
- It is a better idea to set the original exception as the “cause” of the new exception :
```Java
try { access the database } 
catch (SQLException original) 
{ 
	var e = new ServletException("database error");
	e.initCause(original); 
	throw e; 
}
```
- When the exception is caught, the original exception can be retrieved :
```Java
Throwable original = caughtException.getCause();
```

### The finally Clause
- The code in the finally clause executes whether or not an exception is caught or occurred.
- You can use the finally clause without a catch clause.
- Suppose you exit the middle of a `try` block with a return statement. Before the method returns, the `finally` block is executed. If the finally block also contains a return statement, then it masks the original return value.

### The try-with-Resources Statement
- As of Java 7, there is a useful shortcut to the code pattern :
```Java
open a resource 
try { work with the resource } 
finally { close the resource }
```
- provided the resource belongs to a class that implements the `AutoCloseable` interface. That interface has a single method :
```Java
void close() throws Exception
```
- There is also a `Closeable` interface. It is a `subinterface` of `AutoCloseable`, also with a single close method. However, that method is declared to throw an `IOException`.
- In its simplest variant, the try-with-resources statement has the form :

```Java
try (Resource res = . . .) 
{ 
	work with res 
}
```

- When the try block exits, then `res.close()` is called automatically.
- Here is a typical example—reading all words of a file :

```Java
try (var in = new Scanner( new FileInputStream("/usr/share/dict/words"), StandardCharsets.UTF_8))
{ 
	while (in.hasNext()) System.out.println(in.next()); 
}
```

- When the block exits normally, or when there was an exception, the `in.close()` method is called, exactly as if you had used a `finally` block.
- You can specify multiple resources. For example :

```Java
try 
(
var in = new Scanner( new FileInputStream("/usr/share/dict/words"), StandardCharsets.UTF_8); 
var out = new PrintWriter("out.txt", StandardCharsets.UTF_8)
) 
{ 
	while (in.hasNext()) out.println(in.next().toUpperCase()); 
}
```

- No matter how the block exits, both `in` and `out` are closed.
- you can provide previously declared effectively `final` variables in the try header :

```Java
public static void printAll(String[] lines, PrintWriter out) 
{ 
	try (out) // effectively final variable
	{ 
		 for (String line : lines) out.println(line); 
	} // out.close() called here 
}
```

- A try-with-resources statement can itself have `catch` clauses and even a `finally` clause. These are executed after closing the resources.

### Analyzing Stack Trace Elements
- A stack trace is a listing of all pending method calls at a particular point in the execution of a program.
- You can access the text description of a stack trace by calling the `printStackTrace` method of the `Throwable` class.

```Java
var t = new Throwable(); 
var out = new StringWriter(); 
t.printStackTrace(new PrintWriter(out)); 
String description = out.toString();
```

- A more flexible approach is the `StackWalker` class that yields a stream of `StackWalker.StackFrame` instances, each describing one stack frame. You can iterate over the stack frames with this call:

```Java
StackWalker walker = StackWalker.getInstance(); walker.forEach(frame -> analyze frame)
```
- If you want to process the Stream lazily, call

```Java
walker.walk(stream -> process stream)
```

#### Example

![](Pasted_image_20230812140058.png)

#### API

![](Pasted_image_20230812140227.png)

# Tips for Using Exceptions

# Using Assertions #unfinished 

# Logging #unfinished 

# Debugging Tips
